import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthedContext";
import { UserProvider } from "@/context/UserContext";
import { ModalProvider } from "@/providers/modal-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"]
});

export const metadata: Metadata = {
  title: "Crafto",
  description: "Generated by Vaishnavi Solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistPoppins.variable} antialiased`}
      >
        <AuthProvider>
          <UserProvider>
          <main>  {children}</main>
          <Toaster />
          <ModalProvider  />
          </UserProvider>

        </AuthProvider>
      </body>
    </html>
  );
}
